<?php

$_ENV['bootstrap_main_css']   = 'http://'.$_SETTINGS['site']['domain'].$_SETTINGS['site']['folder'].'template/stylesheets/bootstrap.css';
$_ENV['bootstrap_theme_css']  = 'http://'.$_SETTINGS['site']['domain'].$_SETTINGS['site']['folder'].'template/stylesheets/bootstrap-theme.css';
$_ENV['main_stylesheet']      = 'http://'.$_SETTINGS['site']['domain'].$_SETTINGS['site']['folder'].'template/stylesheets/stylesheet.css';
$_ENV['main_js']              = 'http://'.$_SETTINGS['site']['domain'].$_SETTINGS['site']['folder'].'template/javascript/main.js';
$_ENV['bootstrap_js']         = 'http://'.$_SETTINGS['site']['domain'].$_SETTINGS['site']['folder'].'template/javascript/bootstrap.min.js';
$_ENV['application_url']      = 'http://'.$_SETTINGS['site']['domain'].$_SETTINGS['site']['folder'];

?>