<?php
$PAGES['search_depositors_url']                                = 'index.php?controller=depositor&action=list';
$PAGES['create_depositors_url']                                = 'index.php?controller=depositor&action=create';
$PAGES['insert_depositors_url']                                = 'index.php';
$PAGES['depositor_details_url']                                = 'index.php?controller=depositor&action=read&id=';
$PAGES['host_info_url']                                        = 'index.php?action=hostinfo';
$PAGES['exit_url']                                             = 'index.php?controller=auth&action=exit';
?>