<?php
$PAGES['search_depositors_url']                                = $_ENV['application_url'].'?controller=depositor&action=list';
$PAGES['create_depositors_url']                                = $_ENV['application_url'].'?controller=depositor&action=create';
$PAGES['insert_depositors_url']                                = $_ENV['application_url'];
$PAGES['host_info_url']                                        = $_ENV['application_url'].'?action=hostinfo';
$PAGES['exit_url']                                             = $_ENV['application_url'].'?controller=auth&action=exit';
?>